import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My First Next.js App</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to My First Next.js App!</h1>
        <p>This is a simple Next.js app created with JavaScript.</p>

        {/* Button to navigate to the homepage */}
        <Link href="/home">
        <button
          style={{
            padding: '12px 24px',
            marginTop: '20px',
            cursor: 'pointer',
            backgroundColor: '#0070f3', // Nice blue color
            color: 'white',
            border: 'none',
            borderRadius: '8px', // Rounded corners
            fontSize: '16px',
            fontWeight: 'bold',
            transition: 'background-color 0.3s ease, transform 0.2s ease',
          }}
          >
        Go to Home Page
        </button>

        </Link>
      </main>

      <footer>
        <p>Powered by Next.js</p>
      </footer>
    </div>
  );
}
